// check-sql-boundaries enforces the maintained persistence/sqlc boundary.
// This is a review guard, not a security sandbox or a replacement for type checking.
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

const metadataPath = "internal/database/migration_metadata.go"

var metadataSQL = map[string]string{
	"migrationTablesSQL":         "SELECT to_regclass('goose_db_version') IS NOT NULL, to_regclass('schema_migrations') IS NOT NULL",
	"migrationRowsSQL":           "SELECT version_id, is_applied, checksum FROM goose_db_version ORDER BY id",
	"migrationChecksumColumnSQL": "ALTER TABLE goose_db_version ADD COLUMN checksum text",
	"migrationChecksumSQL":       "UPDATE goose_db_version SET checksum=$2 WHERE version_id=$1",
	"migrationSessionLockSQL":    "SELECT pg_advisory_lock($1)",
	"migrationSessionUnlockSQL":  "SELECT pg_advisory_unlock($1)",
}

// Goose's database/sql Store owns its version ledger, which sqlc does not model.
// Inventory the exception by receiver/function AND named statement, never a file
// exemption. Changes to this inventory require review alongside the adapter.
var metadataCalls = map[string]map[string]string{
	"schemaVersions": {
		"QueryRow": "migrationTablesSQL", "Query": "migrationRowsSQL", "Scan": "",
	},
	"checksumStore.TableExists": {
		"QueryRowContext": "migrationTablesSQL", "Scan": "",
	},
	"checksumStore.CreateVersionTable": {"ExecContext": "migrationChecksumColumnSQL"},
	"checksumStore.Insert":             {"ExecContext": "migrationChecksumSQL"},
	"checksumStore.ListMigrations":     {"QueryContext": "migrationRowsSQL"},
	"validateLedger":                   {"Scan": ""},
	"migrationLocker.SessionLock":      {"ExecContext": "migrationSessionLockSQL"},
	"migrationLocker.SessionUnlock": {
		"QueryRowContext": "migrationSessionUnlockSQL", "Scan": "",
	},
}

var driverMethods = map[string]bool{
	"Exec": true, "ExecContext": true, "Query": true, "QueryContext": true,
	"QueryRow": true, "QueryRowContext": true, "Scan": true,
	"Prepare": true, "PrepareContext": true, "SendBatch": true,
	"CopyFrom": true, "PgConn": true,
}

func functionName(fn *ast.FuncDecl) string {
	name := fn.Name.Name
	if fn.Recv != nil && len(fn.Recv.List) == 1 {
		receiver := fn.Recv.List[0].Type
		if pointer, ok := receiver.(*ast.StarExpr); ok {
			receiver = pointer.X
		}
		if ident, ok := receiver.(*ast.Ident); ok {
			name = ident.Name + "." + name
		}
	}
	return name
}

func normalized(value string) string { return strings.Join(strings.Fields(value), " ") }

// Conservatively reject metadata names declared anywhere inside the function,
// even in disjoint scopes. This keeps the adapter easy to review without loading
// application dependencies or relying on deprecated parser object resolution.
func shadows(fn *ast.FuncDecl, name string) bool {
	found := false
	mark := func(expression ast.Expr) {
		if ident, ok := expression.(*ast.Ident); ok && ident.Name == name {
			found = true
		}
	}
	ast.Inspect(fn, func(node ast.Node) bool {
		switch node := node.(type) {
		case *ast.ValueSpec:
			for _, ident := range node.Names {
				mark(ident)
			}
		case *ast.Field:
			for _, ident := range node.Names {
				mark(ident)
			}
		case *ast.AssignStmt:
			if node.Tok == token.DEFINE {
				for _, expression := range node.Lhs {
					mark(expression)
				}
			}
		case *ast.RangeStmt:
			if node.Tok == token.DEFINE {
				mark(node.Key)
				mark(node.Value)
			}
		}
		return true
	})
	return found
}

func checkFile(path string, source []byte) []string {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, source, parser.ParseComments|parser.SkipObjectResolution)
	if err != nil {
		return []string{err.Error()}
	}
	if strings.HasPrefix(path, "internal/database/sqlc/") {
		// The companion sqlc check compares every generated byte and filename.
		if file.Name.Name == "sqlc" && ast.IsGenerated(file) &&
			strings.Contains(string(source), "// Code generated by sqlc. DO NOT EDIT.") {
			return nil
		}
		return []string{path + ": generated directory must contain genuine sqlc output"}
	}
	var failures []string
	report := func(node ast.Node, message string) {
		failures = append(failures, fmt.Sprintf("%s: %s", fset.Position(node.Pos()), message))
	}
	constants := map[string]string{}
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.CONST {
			continue
		}
		for _, spec := range gen.Specs {
			value := spec.(*ast.ValueSpec)
			for i, name := range value.Names {
				if i >= len(value.Values) {
					continue
				}
				if literal, ok := value.Values[i].(*ast.BasicLit); ok && literal.Kind == token.STRING {
					text, err := strconv.Unquote(literal.Value)
					if err == nil {
						constants[name.Name] = normalized(text)
					}
				}
			}
		}
	}
	allowed := map[*ast.SelectorExpr]bool{}
	if path == metadataPath {
		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Body == nil {
				continue
			}
			inventory := metadataCalls[functionName(fn)]
			ast.Inspect(fn.Body, func(node ast.Node) bool {
				call, ok := node.(*ast.CallExpr)
				if !ok {
					return true
				}
				selector, ok := call.Fun.(*ast.SelectorExpr)
				if !ok {
					return true
				}
				statement, ok := inventory[selector.Sel.Name]
				if !ok {
					return true
				}
				if statement == "" {
					allowed[selector] = true
					return true
				}
				if len(call.Args) >= 2 {
					ident, ok := call.Args[1].(*ast.Ident)
					if ok && ident.Name == statement && !shadows(fn, statement) &&
						constants[statement] != "" && constants[statement] == normalized(metadataSQL[statement]) {
						allowed[selector] = true
					}
				}
				return true
			})
		}
	}
	ast.Inspect(file, func(node ast.Node) bool {
		if selector, ok := node.(*ast.SelectorExpr); ok && driverMethods[selector.Sel.Name] && !allowed[selector] {
			report(selector, "direct "+selector.Sel.Name+" is outside the sqlc/Goose metadata boundary")
		}
		return true
	})
	return failures
}

func check(root string) ([]string, error) {
	var failures []string
	for _, directory := range []string{"internal/auth", "internal/database"} {
		err := filepath.WalkDir(filepath.Join(root, directory), func(path string, entry fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			name, err := filepath.Rel(root, path)
			if err != nil {
				return err
			}
			name = filepath.ToSlash(name)
			if entry.IsDir() {
				if name == "internal/auth/authtest" {
					return filepath.SkipDir
				}
				return nil
			}
			if !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
				return nil
			}
			if entry.Type()&os.ModeSymlink != 0 {
				return fmt.Errorf("%s: persistence source cannot be a symlink", name)
			}
			source, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			failures = append(failures, checkFile(name, source)...)
			return nil
		})
		if err != nil {
			return nil, err
		}
	}
	return failures, nil
}

func main() {
	failures, err := check(".")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	for _, failure := range failures {
		fmt.Fprintln(os.Stderr, failure)
	}
	if len(failures) != 0 {
		os.Exit(1)
	}
	fmt.Println("Maintained persistence uses sqlc; Goose metadata exceptions match the reviewed inventory.")
}
