package main

import (
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

func TestMaintainedBoundary(t *testing.T) {
	for _, tc := range []struct {
		name, path, source string
		wantFailure        bool
	}{
		{"sqlc call", "internal/auth/store.go", "package auth\nfunc f(){ queries.FindUser(ctx, name) }", false},
		{"driver call", "internal/database/store.go", "package database\nfunc f(){ tx.QueryRow(ctx, query).Scan(&id) }", true},
		{"method alias", "internal/auth/store.go", "package auth\nvar query = pool.Query", true},
		{"method expression", "internal/auth/store.go", "package auth\nvar query = (*Pool).Query", true},
		{"prepared statement", "internal/auth/store.go", "package auth\nfunc f(){ pool.Prepare(ctx, name, query) }", true},
		{"generated header elsewhere", "internal/auth/generated.go", "// Code generated by sqlc. DO NOT EDIT.\npackage auth\nfunc f(){ pool.Exec(ctx, query) }", true},
		{"real generated output", "internal/database/sqlc/db.go", "// Code generated by sqlc. DO NOT EDIT.\npackage sqlc\nfunc f(){ pool.Exec(ctx, query) }", false},
		{"handwritten in generated dir", "internal/database/sqlc/extra.go", "package sqlc\nfunc f(){}", true},
		{"migrate has no exemption", "internal/database/migrate.go", "package database\nfunc f(){ tx.Exec(ctx, query) }", true},
		{"metadata has no blanket exemption", metadataPath, "package database\nfunc f(){ tx.Exec(ctx, query) }", true},
		{"invalid syntax", "internal/database/store.go", "package database\nfunc f(", true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			failures := checkFile(tc.path, []byte(tc.source))
			if (len(failures) != 0) != tc.wantFailure {
				t.Fatalf("failures = %v; want failure %v", failures, tc.wantFailure)
			}
		})
	}
}

func TestMetadataInventory(t *testing.T) {
	source := `package database
const migrationTablesSQL = ` + strconv.Quote(metadataSQL["migrationTablesSQL"]) + `
func schemaVersions() { tx.QueryRow(ctx, migrationTablesSQL).Scan(&goose, &legacy) }
`
	if failures := checkFile(metadataPath, []byte(source)); len(failures) != 0 {
		t.Fatal(failures)
	}
	for _, changed := range []string{
		strings.ReplaceAll(source, "goose_db_version", "users"),
		strings.Replace(source, "func schemaVersions", "func arbitrary", 1),
		strings.Replace(source, "tx.QueryRow(ctx, migrationTablesSQL)", `tx.QueryRow(ctx, "SELECT * FROM users")`, 1),
		strings.Replace(source, "{ tx.QueryRow", `{ const migrationTablesSQL = "SELECT * FROM users"; tx.QueryRow`, 1),
		strings.Replace(source, "{ tx.QueryRow", `{ migrationTablesSQL := "SELECT * FROM users"; tx.QueryRow`, 1),
		strings.Replace(source, "{ tx.QueryRow", "{ query := tx.QueryRow; query", 1),
	} {
		if failures := checkFile(metadataPath, []byte(changed)); len(failures) == 0 {
			t.Fatalf("unexpectedly accepted changed metadata:\n%s", changed)
		}
	}
	for function, methods := range metadataCalls {
		for method, statement := range methods {
			if statement == "" {
				continue
			}
			declaration := "func " + function + "()"
			if parts := strings.Split(function, "."); len(parts) == 2 {
				declaration = "func (s *" + parts[0] + ") " + parts[1] + "()"
			}
			source := "package database\nconst " + statement + " = " + strconv.Quote(metadataSQL[statement]) +
				"\n" + declaration + " { db." + method + "(ctx, " + statement + ") }\n"
			if failures := checkFile(metadataPath, []byte(source)); len(failures) != 0 {
				t.Fatalf("%s: %v", function, failures)
			}
		}
	}
}

func TestScopedFixtures(t *testing.T) {
	root := t.TempDir()
	for _, path := range []string{
		"internal/auth/authtest/fixture.go",
		"internal/auth/store_test.go",
		"internal/database/store_test.go",
		"internal/database/testdata/maintained.go",
	} {
		path = filepath.Join(root, path)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte("package fixture\nfunc f(){ tx.Exec(ctx, query) }\n"), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	failures, err := check(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(failures) != 1 || !strings.Contains(failures[0], "testdata/maintained.go") {
		t.Fatalf("only explicitly scoped fixtures may bypass: %v", failures)
	}
}
