// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"
	"time"
)

const authenticateSession = `-- name: AuthenticateSession :one
SELECT s.id::text AS session_id, s.kind, u.id::text AS user_id,
    u.username, u.role, s.expires_at
FROM sessions s JOIN users u ON u.id = s.user_id
WHERE s.token_digest = $1 AND s.kind = $2
    AND s.revoked_at IS NULL AND s.expires_at > clock_timestamp() AND NOT u.disabled
`

type AuthenticateSessionParams struct {
	TokenDigest []byte
	Kind        string
}

type AuthenticateSessionRow struct {
	SessionID string
	Kind      string
	UserID    string
	Username  string
	Role      string
	ExpiresAt time.Time
}

func (q *Queries) AuthenticateSession(ctx context.Context, arg AuthenticateSessionParams) (AuthenticateSessionRow, error) {
	row := q.db.QueryRow(ctx, authenticateSession, arg.TokenDigest, arg.Kind)
	var i AuthenticateSessionRow
	err := row.Scan(
		&i.SessionID,
		&i.Kind,
		&i.UserID,
		&i.Username,
		&i.Role,
		&i.ExpiresAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, token_digest, user_id, kind, expires_at)
VALUES (
    $1::text::uuid,
    $2,
    $3::text::uuid,
    $4,
    clock_timestamp() + $5::double precision * interval '1 second'
)
RETURNING expires_at
`

type CreateSessionParams struct {
	ID          string
	TokenDigest []byte
	UserID      string
	Kind        string
	TtlSeconds  float64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.TokenDigest,
		arg.UserID,
		arg.Kind,
		arg.TtlSeconds,
	)
	var expires_at time.Time
	err := row.Scan(&expires_at)
	return expires_at, err
}

const findLoginUser = `-- name: FindLoginUser :one
SELECT id::text, username, role, password_hash, disabled
FROM users WHERE username = $1
`

type FindLoginUserRow struct {
	ID           string
	Username     string
	Role         string
	PasswordHash string
	Disabled     bool
}

func (q *Queries) FindLoginUser(ctx context.Context, username string) (FindLoginUserRow, error) {
	row := q.db.QueryRow(ctx, findLoginUser, username)
	var i FindLoginUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.PasswordHash,
		&i.Disabled,
	)
	return i, err
}

const insertAuthEvent = `-- name: InsertAuthEvent :exec
INSERT INTO auth_events (id, actor_id, target_id, session_id, connection_id, action, outcome)
VALUES (
    $1::text::uuid,
    NULLIF($2::text, '')::uuid,
    NULLIF($3::text, '')::uuid,
    NULLIF($4::text, '')::uuid,
    NULLIF($5::text, '')::uuid,
    $6,
    $7
)
`

type InsertAuthEventParams struct {
	ID           string
	ActorID      string
	TargetID     string
	SessionID    string
	ConnectionID string
	Action       string
	Outcome      string
}

func (q *Queries) InsertAuthEvent(ctx context.Context, arg InsertAuthEventParams) error {
	_, err := q.db.Exec(ctx, insertAuthEvent,
		arg.ID,
		arg.ActorID,
		arg.TargetID,
		arg.SessionID,
		arg.ConnectionID,
		arg.Action,
		arg.Outcome,
	)
	return err
}

const lockLoginUser = `-- name: LockLoginUser :one
SELECT username, role, password_hash, disabled
FROM users WHERE id = $1::text::uuid FOR UPDATE
`

type LockLoginUserRow struct {
	Username     string
	Role         string
	PasswordHash string
	Disabled     bool
}

func (q *Queries) LockLoginUser(ctx context.Context, id string) (LockLoginUserRow, error) {
	row := q.db.QueryRow(ctx, lockLoginUser, id)
	var i LockLoginUserRow
	err := row.Scan(
		&i.Username,
		&i.Role,
		&i.PasswordHash,
		&i.Disabled,
	)
	return i, err
}

const lockMutationUsers = `-- name: LockMutationUsers :exec
SELECT id FROM users
WHERE id = $1::text::uuid
    OR id = NULLIF($2::text, '')::uuid
    OR username = NULLIF($3::text, '')
ORDER BY id FOR UPDATE
`

type LockMutationUsersParams struct {
	ActorID        string
	TargetID       string
	TargetUsername string
}

// Consistent ordering serializes issuance/revocation without opposing-admin
// deadlocks. A target addressed by username is locked by this same statement,
// so resolving a name never splits acquisition into two ordered waits.
func (q *Queries) LockMutationUsers(ctx context.Context, arg LockMutationUsersParams) error {
	_, err := q.db.Exec(ctx, lockMutationUsers, arg.ActorID, arg.TargetID, arg.TargetUsername)
	return err
}

const recheckSession = `-- name: RecheckSession :one
SELECT s.id::text AS session_id, s.kind, u.id::text AS user_id,
    u.username, u.role, s.expires_at
FROM sessions s JOIN users u ON u.id = s.user_id
WHERE s.id = $1::text::uuid
    AND s.user_id = $2::text::uuid AND s.kind = $3
    AND s.revoked_at IS NULL AND s.expires_at > clock_timestamp() AND NOT u.disabled
FOR UPDATE OF s
`

type RecheckSessionParams struct {
	SessionID string
	UserID    string
	Kind      string
}

type RecheckSessionRow struct {
	SessionID string
	Kind      string
	UserID    string
	Username  string
	Role      string
	ExpiresAt time.Time
}

func (q *Queries) RecheckSession(ctx context.Context, arg RecheckSessionParams) (RecheckSessionRow, error) {
	row := q.db.QueryRow(ctx, recheckSession, arg.SessionID, arg.UserID, arg.Kind)
	var i RecheckSessionRow
	err := row.Scan(
		&i.SessionID,
		&i.Kind,
		&i.UserID,
		&i.Username,
		&i.Role,
		&i.ExpiresAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = clock_timestamp() WHERE id = $1::text::uuid
`

func (q *Queries) RevokeSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE sessions SET revoked_at = clock_timestamp()
WHERE user_id = $1::text::uuid AND revoked_at IS NULL
`

func (q *Queries) RevokeUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, userID)
	return err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE id = $1::text::uuid)
`

func (q *Queries) UserExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
