// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connections.sql

package sqlc

import (
	"context"
)

const checkConnectionsColumns = `-- name: CheckConnectionsColumns :exec
SELECT id, name, title, description, scope, provider, target, labels, secret_envelope, enabled,
    statement_timeout_ms, max_rows, max_bytes, last_check_outcome, last_check_at, created_at, updated_at
FROM connections LIMIT 0
`

func (q *Queries) CheckConnectionsColumns(ctx context.Context) error {
	_, err := q.db.Exec(ctx, checkConnectionsColumns)
	return err
}

const connectionNameExists = `-- name: ConnectionNameExists :one
SELECT EXISTS(SELECT 1 FROM connections WHERE name = $1)
`

func (q *Queries) ConnectionNameExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, connectionNameExists, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteConnection = `-- name: DeleteConnection :execrows
DELETE FROM connections WHERE id = $1::text::uuid AND NOT enabled
`

func (q *Queries) DeleteConnection(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConnection, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findConnectionByID = `-- name: FindConnectionByID :one
SELECT id, name, title, description, scope, provider, target, labels, secret_envelope, enabled, statement_timeout_ms, max_rows, max_bytes, last_check_outcome, last_check_at, created_at, updated_at FROM connections WHERE id = $1::text::uuid
`

func (q *Queries) FindConnectionByID(ctx context.Context, id string) (Connection, error) {
	row := q.db.QueryRow(ctx, findConnectionByID, id)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.Scope,
		&i.Provider,
		&i.Target,
		&i.Labels,
		&i.SecretEnvelope,
		&i.Enabled,
		&i.StatementTimeoutMs,
		&i.MaxRows,
		&i.MaxBytes,
		&i.LastCheckOutcome,
		&i.LastCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findConnectionByName = `-- name: FindConnectionByName :one
SELECT id, name, title, description, scope, provider, target, labels, secret_envelope, enabled, statement_timeout_ms, max_rows, max_bytes, last_check_outcome, last_check_at, created_at, updated_at FROM connections WHERE name = $1
`

func (q *Queries) FindConnectionByName(ctx context.Context, name string) (Connection, error) {
	row := q.db.QueryRow(ctx, findConnectionByName, name)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.Scope,
		&i.Provider,
		&i.Target,
		&i.Labels,
		&i.SecretEnvelope,
		&i.Enabled,
		&i.StatementTimeoutMs,
		&i.MaxRows,
		&i.MaxBytes,
		&i.LastCheckOutcome,
		&i.LastCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertConnection = `-- name: InsertConnection :one
INSERT INTO connections (id, name, title, description, scope, provider, target, labels,
    secret_envelope, statement_timeout_ms, max_rows, max_bytes)
VALUES (
    $1::text::uuid, $2, $3, $4,
    $5, $6, $7::jsonb, $8::jsonb,
    $9, $10, $11, $12
)
RETURNING id, name, title, description, scope, provider, target, labels, secret_envelope, enabled, statement_timeout_ms, max_rows, max_bytes, last_check_outcome, last_check_at, created_at, updated_at
`

type InsertConnectionParams struct {
	ID                 string
	Name               string
	Title              string
	Description        string
	Scope              string
	Provider           string
	Target             []byte
	Labels             []byte
	SecretEnvelope     string
	StatementTimeoutMs int32
	MaxRows            int32
	MaxBytes           int32
}

func (q *Queries) InsertConnection(ctx context.Context, arg InsertConnectionParams) (Connection, error) {
	row := q.db.QueryRow(ctx, insertConnection,
		arg.ID,
		arg.Name,
		arg.Title,
		arg.Description,
		arg.Scope,
		arg.Provider,
		arg.Target,
		arg.Labels,
		arg.SecretEnvelope,
		arg.StatementTimeoutMs,
		arg.MaxRows,
		arg.MaxBytes,
	)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.Scope,
		&i.Provider,
		&i.Target,
		&i.Labels,
		&i.SecretEnvelope,
		&i.Enabled,
		&i.StatementTimeoutMs,
		&i.MaxRows,
		&i.MaxBytes,
		&i.LastCheckOutcome,
		&i.LastCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConnections = `-- name: ListConnections :many
SELECT id, name, title, description, scope, provider, target, labels, secret_envelope, enabled, statement_timeout_ms, max_rows, max_bytes, last_check_outcome, last_check_at, created_at, updated_at FROM connections
WHERE labels @> COALESCE($1::jsonb, '{}'::jsonb)
    AND NOT EXISTS (
        SELECT 1 FROM jsonb_array_elements(COALESCE($2::jsonb, '[]'::jsonb)) AS excluded
        WHERE labels @> excluded
    )
    AND labels ?& COALESCE($3::text[], '{}'::text[])
ORDER BY name LIMIT $4::integer
`

type ListConnectionsParams struct {
	Contains  []byte
	Excludes  []byte
	Keys      []string
	LimitRows int32
}

// Selector terms compile to containment (equals), negated containment
// (not-equals) and key existence; empty or NULL inputs match every row. The
// caller requests one row beyond its bound to detect truncation.
func (q *Queries) ListConnections(ctx context.Context, arg ListConnectionsParams) ([]Connection, error) {
	rows, err := q.db.Query(ctx, listConnections,
		arg.Contains,
		arg.Excludes,
		arg.Keys,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Connection
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.Description,
			&i.Scope,
			&i.Provider,
			&i.Target,
			&i.Labels,
			&i.SecretEnvelope,
			&i.Enabled,
			&i.StatementTimeoutMs,
			&i.MaxRows,
			&i.MaxBytes,
			&i.LastCheckOutcome,
			&i.LastCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockConnection = `-- name: LockConnection :one
SELECT id, name, title, description, scope, provider, target, labels, secret_envelope, enabled, statement_timeout_ms, max_rows, max_bytes, last_check_outcome, last_check_at, created_at, updated_at FROM connections WHERE id = $1::text::uuid FOR UPDATE
`

func (q *Queries) LockConnection(ctx context.Context, id string) (Connection, error) {
	row := q.db.QueryRow(ctx, lockConnection, id)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.Scope,
		&i.Provider,
		&i.Target,
		&i.Labels,
		&i.SecretEnvelope,
		&i.Enabled,
		&i.StatementTimeoutMs,
		&i.MaxRows,
		&i.MaxBytes,
		&i.LastCheckOutcome,
		&i.LastCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setConnectionCheck = `-- name: SetConnectionCheck :one
UPDATE connections SET last_check_outcome = $1::text, last_check_at = clock_timestamp()
WHERE id = $2::text::uuid
RETURNING id, name, title, description, scope, provider, target, labels, secret_envelope, enabled, statement_timeout_ms, max_rows, max_bytes, last_check_outcome, last_check_at, created_at, updated_at
`

type SetConnectionCheckParams struct {
	Outcome string
	ID      string
}

func (q *Queries) SetConnectionCheck(ctx context.Context, arg SetConnectionCheckParams) (Connection, error) {
	row := q.db.QueryRow(ctx, setConnectionCheck, arg.Outcome, arg.ID)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.Scope,
		&i.Provider,
		&i.Target,
		&i.Labels,
		&i.SecretEnvelope,
		&i.Enabled,
		&i.StatementTimeoutMs,
		&i.MaxRows,
		&i.MaxBytes,
		&i.LastCheckOutcome,
		&i.LastCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setConnectionEnabled = `-- name: SetConnectionEnabled :one
UPDATE connections SET enabled = $1, updated_at = clock_timestamp()
WHERE id = $2::text::uuid
RETURNING id, name, title, description, scope, provider, target, labels, secret_envelope, enabled, statement_timeout_ms, max_rows, max_bytes, last_check_outcome, last_check_at, created_at, updated_at
`

type SetConnectionEnabledParams struct {
	Enabled bool
	ID      string
}

func (q *Queries) SetConnectionEnabled(ctx context.Context, arg SetConnectionEnabledParams) (Connection, error) {
	row := q.db.QueryRow(ctx, setConnectionEnabled, arg.Enabled, arg.ID)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.Scope,
		&i.Provider,
		&i.Target,
		&i.Labels,
		&i.SecretEnvelope,
		&i.Enabled,
		&i.StatementTimeoutMs,
		&i.MaxRows,
		&i.MaxBytes,
		&i.LastCheckOutcome,
		&i.LastCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setConnectionSecret = `-- name: SetConnectionSecret :one
UPDATE connections SET secret_envelope = $1,
    last_check_outcome = NULL, last_check_at = NULL, updated_at = clock_timestamp()
WHERE id = $2::text::uuid
RETURNING id, name, title, description, scope, provider, target, labels, secret_envelope, enabled, statement_timeout_ms, max_rows, max_bytes, last_check_outcome, last_check_at, created_at, updated_at
`

type SetConnectionSecretParams struct {
	SecretEnvelope string
	ID             string
}

// Replacing credentials invalidates the last check.
func (q *Queries) SetConnectionSecret(ctx context.Context, arg SetConnectionSecretParams) (Connection, error) {
	row := q.db.QueryRow(ctx, setConnectionSecret, arg.SecretEnvelope, arg.ID)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.Scope,
		&i.Provider,
		&i.Target,
		&i.Labels,
		&i.SecretEnvelope,
		&i.Enabled,
		&i.StatementTimeoutMs,
		&i.MaxRows,
		&i.MaxBytes,
		&i.LastCheckOutcome,
		&i.LastCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateConnection = `-- name: UpdateConnection :one
UPDATE connections SET
    name = COALESCE($1::text, name),
    title = COALESCE($2::text, title),
    description = COALESCE($3::text, description),
    scope = COALESCE($4::text, scope),
    target = COALESCE($5::jsonb, target),
    labels = COALESCE($6::jsonb, labels),
    statement_timeout_ms = COALESCE($7::integer, statement_timeout_ms),
    max_rows = COALESCE($8::integer, max_rows),
    max_bytes = COALESCE($9::integer, max_bytes),
    updated_at = clock_timestamp()
WHERE id = $10::text::uuid
RETURNING id, name, title, description, scope, provider, target, labels, secret_envelope, enabled, statement_timeout_ms, max_rows, max_bytes, last_check_outcome, last_check_at, created_at, updated_at
`

type UpdateConnectionParams struct {
	Name               *string
	Title              *string
	Description        *string
	Scope              *string
	Target             []byte
	Labels             []byte
	StatementTimeoutMs *int32
	MaxRows            *int32
	MaxBytes           *int32
	ID                 string
}

func (q *Queries) UpdateConnection(ctx context.Context, arg UpdateConnectionParams) (Connection, error) {
	row := q.db.QueryRow(ctx, updateConnection,
		arg.Name,
		arg.Title,
		arg.Description,
		arg.Scope,
		arg.Target,
		arg.Labels,
		arg.StatementTimeoutMs,
		arg.MaxRows,
		arg.MaxBytes,
		arg.ID,
	)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.Scope,
		&i.Provider,
		&i.Target,
		&i.Labels,
		&i.SecretEnvelope,
		&i.Enabled,
		&i.StatementTimeoutMs,
		&i.MaxRows,
		&i.MaxBytes,
		&i.LastCheckOutcome,
		&i.LastCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
