// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grants.sql

package sqlc

import (
	"context"
	"time"
)

const checkGrantsColumns = `-- name: CheckGrantsColumns :exec
SELECT user_id, connection_id, created_at, created_by FROM grants LIMIT 0
`

func (q *Queries) CheckGrantsColumns(ctx context.Context) error {
	_, err := q.db.Exec(ctx, checkGrantsColumns)
	return err
}

const countConnectionGrants = `-- name: CountConnectionGrants :one
SELECT count(*) FROM grants WHERE connection_id = $1::text::uuid
`

func (q *Queries) CountConnectionGrants(ctx context.Context, connectionID string) (int64, error) {
	row := q.db.QueryRow(ctx, countConnectionGrants, connectionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteGrant = `-- name: DeleteGrant :execrows
DELETE FROM grants WHERE user_id = $1::text::uuid AND connection_id = $2::text::uuid
`

type DeleteGrantParams struct {
	UserID       string
	ConnectionID string
}

func (q *Queries) DeleteGrant(ctx context.Context, arg DeleteGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGrant, arg.UserID, arg.ConnectionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findGrant = `-- name: FindGrant :one
SELECT g.user_id::text AS user_id, u.username, g.connection_id::text AS connection_id, c.name AS connection_name,
    g.created_at, g.created_by::text AS created_by, cb.username AS created_by_username
FROM grants g
    JOIN users u ON u.id = g.user_id
    JOIN connections c ON c.id = g.connection_id
    JOIN users cb ON cb.id = g.created_by
WHERE g.user_id = $1::text::uuid AND g.connection_id = $2::text::uuid
`

type FindGrantParams struct {
	UserID       string
	ConnectionID string
}

type FindGrantRow struct {
	UserID            string
	Username          string
	ConnectionID      string
	ConnectionName    string
	CreatedAt         time.Time
	CreatedBy         string
	CreatedByUsername string
}

func (q *Queries) FindGrant(ctx context.Context, arg FindGrantParams) (FindGrantRow, error) {
	row := q.db.QueryRow(ctx, findGrant, arg.UserID, arg.ConnectionID)
	var i FindGrantRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.ConnectionID,
		&i.ConnectionName,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.CreatedByUsername,
	)
	return i, err
}

const findGrantedConnectionByID = `-- name: FindGrantedConnectionByID :one
SELECT c.id, c.name, c.title, c.description, c.scope, c.provider, c.target, c.labels, c.secret_envelope, c.enabled, c.statement_timeout_ms, c.max_rows, c.max_bytes, c.last_check_outcome, c.last_check_at, c.created_at, c.updated_at FROM connections c JOIN grants g ON g.connection_id = c.id
WHERE g.user_id = $1::text::uuid AND c.id = $2::text::uuid
`

type FindGrantedConnectionByIDParams struct {
	UserID string
	ID     string
}

func (q *Queries) FindGrantedConnectionByID(ctx context.Context, arg FindGrantedConnectionByIDParams) (Connection, error) {
	row := q.db.QueryRow(ctx, findGrantedConnectionByID, arg.UserID, arg.ID)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.Scope,
		&i.Provider,
		&i.Target,
		&i.Labels,
		&i.SecretEnvelope,
		&i.Enabled,
		&i.StatementTimeoutMs,
		&i.MaxRows,
		&i.MaxBytes,
		&i.LastCheckOutcome,
		&i.LastCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findGrantedConnectionByName = `-- name: FindGrantedConnectionByName :one
SELECT c.id, c.name, c.title, c.description, c.scope, c.provider, c.target, c.labels, c.secret_envelope, c.enabled, c.statement_timeout_ms, c.max_rows, c.max_bytes, c.last_check_outcome, c.last_check_at, c.created_at, c.updated_at FROM connections c JOIN grants g ON g.connection_id = c.id
WHERE g.user_id = $1::text::uuid AND c.name = $2
`

type FindGrantedConnectionByNameParams struct {
	UserID string
	Name   string
}

func (q *Queries) FindGrantedConnectionByName(ctx context.Context, arg FindGrantedConnectionByNameParams) (Connection, error) {
	row := q.db.QueryRow(ctx, findGrantedConnectionByName, arg.UserID, arg.Name)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.Scope,
		&i.Provider,
		&i.Target,
		&i.Labels,
		&i.SecretEnvelope,
		&i.Enabled,
		&i.StatementTimeoutMs,
		&i.MaxRows,
		&i.MaxBytes,
		&i.LastCheckOutcome,
		&i.LastCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserIDByUsername = `-- name: FindUserIDByUsername :one
SELECT id::text FROM users WHERE username = $1
`

func (q *Queries) FindUserIDByUsername(ctx context.Context, username string) (string, error) {
	row := q.db.QueryRow(ctx, findUserIDByUsername, username)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertGrant = `-- name: InsertGrant :one
INSERT INTO grants (user_id, connection_id, created_by)
VALUES ($1::text::uuid, $2::text::uuid, $3::text::uuid)
ON CONFLICT DO NOTHING
RETURNING user_id::text, connection_id::text, created_at, created_by::text
`

type InsertGrantParams struct {
	UserID       string
	ConnectionID string
	CreatedBy    string
}

type InsertGrantRow struct {
	UserID       string
	ConnectionID string
	CreatedAt    time.Time
	CreatedBy    string
}

// A repeated grant is a no-op: no row is returned and the caller reads the
// existing one.
func (q *Queries) InsertGrant(ctx context.Context, arg InsertGrantParams) (InsertGrantRow, error) {
	row := q.db.QueryRow(ctx, insertGrant, arg.UserID, arg.ConnectionID, arg.CreatedBy)
	var i InsertGrantRow
	err := row.Scan(
		&i.UserID,
		&i.ConnectionID,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listGrantedConnectionNames = `-- name: ListGrantedConnectionNames :many
SELECT c.name FROM connections c JOIN grants g ON g.connection_id = c.id
WHERE g.user_id = $1::text::uuid
ORDER BY c.name LIMIT $2::integer
`

type ListGrantedConnectionNamesParams struct {
	UserID    string
	LimitRows int32
}

func (q *Queries) ListGrantedConnectionNames(ctx context.Context, arg ListGrantedConnectionNamesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listGrantedConnectionNames, arg.UserID, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantedConnections = `-- name: ListGrantedConnections :many
SELECT c.id, c.name, c.title, c.description, c.scope, c.provider, c.target, c.labels, c.secret_envelope, c.enabled, c.statement_timeout_ms, c.max_rows, c.max_bytes, c.last_check_outcome, c.last_check_at, c.created_at, c.updated_at FROM connections c JOIN grants g ON g.connection_id = c.id
WHERE g.user_id = $1::text::uuid
    AND c.labels @> COALESCE($2::jsonb, '{}'::jsonb)
    AND NOT EXISTS (
        SELECT 1 FROM jsonb_array_elements(COALESCE($3::jsonb, '[]'::jsonb)) AS excluded
        WHERE c.labels @> excluded
    )
    AND c.labels ?& COALESCE($4::text[], '{}'::text[])
ORDER BY c.name LIMIT $5::integer
`

type ListGrantedConnectionsParams struct {
	UserID    string
	Contains  []byte
	Excludes  []byte
	Keys      []string
	LimitRows int32
}

// The member listing: granted connections only, same selector semantics as
// the administrator listing, one row beyond the bound for truncation.
func (q *Queries) ListGrantedConnections(ctx context.Context, arg ListGrantedConnectionsParams) ([]Connection, error) {
	rows, err := q.db.Query(ctx, listGrantedConnections,
		arg.UserID,
		arg.Contains,
		arg.Excludes,
		arg.Keys,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Connection
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.Description,
			&i.Scope,
			&i.Provider,
			&i.Target,
			&i.Labels,
			&i.SecretEnvelope,
			&i.Enabled,
			&i.StatementTimeoutMs,
			&i.MaxRows,
			&i.MaxBytes,
			&i.LastCheckOutcome,
			&i.LastCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrants = `-- name: ListGrants :many
SELECT g.user_id::text AS user_id, u.username, g.connection_id::text AS connection_id, c.name AS connection_name,
    g.created_at, g.created_by::text AS created_by, cb.username AS created_by_username
FROM grants g
    JOIN users u ON u.id = g.user_id
    JOIN connections c ON c.id = g.connection_id
    JOIN users cb ON cb.id = g.created_by
WHERE ($1::text IS NULL OR g.user_id = $1::text::uuid)
    AND ($2::text IS NULL OR g.connection_id = $2::text::uuid)
ORDER BY u.username, c.name LIMIT $3::integer
`

type ListGrantsParams struct {
	UserID       *string
	ConnectionID *string
	LimitRows    int32
}

type ListGrantsRow struct {
	UserID            string
	Username          string
	ConnectionID      string
	ConnectionName    string
	CreatedAt         time.Time
	CreatedBy         string
	CreatedByUsername string
}

// NULL filters match every row; the caller requests one row beyond its bound.
func (q *Queries) ListGrants(ctx context.Context, arg ListGrantsParams) ([]ListGrantsRow, error) {
	rows, err := q.db.Query(ctx, listGrants, arg.UserID, arg.ConnectionID, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGrantsRow
	for rows.Next() {
		var i ListGrantsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.ConnectionID,
			&i.ConnectionName,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.CreatedByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
