// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grants.sql

package sqlc

import (
	"context"
	"time"
)

const checkGrantsColumns = `-- name: CheckGrantsColumns :exec
SELECT user_id, group_id, connection_id, created_at, created_by FROM grants LIMIT 0
`

func (q *Queries) CheckGrantsColumns(ctx context.Context) error {
	_, err := q.db.Exec(ctx, checkGrantsColumns)
	return err
}

const countConnectionGrants = `-- name: CountConnectionGrants :one
SELECT count(*) FROM grants WHERE connection_id = $1::text::uuid
`

// Both recipient kinds live in this table, so the connection delete guard
// counts them together without knowing that groups exist.
func (q *Queries) CountConnectionGrants(ctx context.Context, connectionID string) (int64, error) {
	row := q.db.QueryRow(ctx, countConnectionGrants, connectionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteGrant = `-- name: DeleteGrant :execrows
DELETE FROM grants
WHERE connection_id = $1::text::uuid
    AND user_id IS NOT DISTINCT FROM $2::text::uuid
    AND group_id IS NOT DISTINCT FROM $3::text::uuid
`

type DeleteGrantParams struct {
	ConnectionID string
	UserID       *string
	GroupID      *string
}

func (q *Queries) DeleteGrant(ctx context.Context, arg DeleteGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGrant, arg.ConnectionID, arg.UserID, arg.GroupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findGrant = `-- name: FindGrant :one
SELECT g.user_id, u.username, g.group_id, gr.name AS group_name,
    g.connection_id, c.name AS connection_name,
    g.created_at, g.created_by, cb.username AS created_by_username
FROM grants g
    LEFT JOIN users u ON u.id = g.user_id
    LEFT JOIN groups gr ON gr.id = g.group_id
    JOIN connections c ON c.id = g.connection_id
    JOIN users cb ON cb.id = g.created_by
WHERE g.connection_id = $1::text::uuid
    AND g.user_id IS NOT DISTINCT FROM $2::text::uuid
    AND g.group_id IS NOT DISTINCT FROM $3::text::uuid
`

type FindGrantParams struct {
	ConnectionID string
	UserID       *string
	GroupID      *string
}

type FindGrantRow struct {
	UserID            *string
	Username          *string
	GroupID           *string
	GroupName         *string
	ConnectionID      string
	ConnectionName    string
	CreatedAt         time.Time
	CreatedBy         string
	CreatedByUsername string
}

// The recipient is matched on both columns at once: IS NOT DISTINCT FROM makes
// the NULL side of the pair part of the key rather than an unmatchable value.
func (q *Queries) FindGrant(ctx context.Context, arg FindGrantParams) (FindGrantRow, error) {
	row := q.db.QueryRow(ctx, findGrant, arg.ConnectionID, arg.UserID, arg.GroupID)
	var i FindGrantRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.GroupID,
		&i.GroupName,
		&i.ConnectionID,
		&i.ConnectionName,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.CreatedByUsername,
	)
	return i, err
}

const findGrantedConnectionByID = `-- name: FindGrantedConnectionByID :one
SELECT c.id, c.name, c.title, c.description, c.scope, c.provider, c.target, c.labels, c.secret_envelope, c.enabled, c.statement_timeout_ms, c.max_rows, c.max_bytes, c.last_check_outcome, c.last_check_at, c.created_at, c.updated_at FROM connections c
WHERE c.id = $1::text::uuid
    AND EXISTS (
        SELECT 1 FROM grants g
        WHERE g.connection_id = c.id
            AND (g.user_id = $2::text::uuid
                OR g.group_id IN (SELECT m.group_id FROM group_members m WHERE m.user_id = $2::text::uuid))
    )
`

type FindGrantedConnectionByIDParams struct {
	ID     string
	UserID string
}

func (q *Queries) FindGrantedConnectionByID(ctx context.Context, arg FindGrantedConnectionByIDParams) (Connection, error) {
	row := q.db.QueryRow(ctx, findGrantedConnectionByID, arg.ID, arg.UserID)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.Scope,
		&i.Provider,
		&i.Target,
		&i.Labels,
		&i.SecretEnvelope,
		&i.Enabled,
		&i.StatementTimeoutMs,
		&i.MaxRows,
		&i.MaxBytes,
		&i.LastCheckOutcome,
		&i.LastCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findGrantedConnectionByName = `-- name: FindGrantedConnectionByName :one
SELECT c.id, c.name, c.title, c.description, c.scope, c.provider, c.target, c.labels, c.secret_envelope, c.enabled, c.statement_timeout_ms, c.max_rows, c.max_bytes, c.last_check_outcome, c.last_check_at, c.created_at, c.updated_at FROM connections c
WHERE c.name = $1
    AND EXISTS (
        SELECT 1 FROM grants g
        WHERE g.connection_id = c.id
            AND (g.user_id = $2::text::uuid
                OR g.group_id IN (SELECT m.group_id FROM group_members m WHERE m.user_id = $2::text::uuid))
    )
`

type FindGrantedConnectionByNameParams struct {
	Name   string
	UserID string
}

func (q *Queries) FindGrantedConnectionByName(ctx context.Context, arg FindGrantedConnectionByNameParams) (Connection, error) {
	row := q.db.QueryRow(ctx, findGrantedConnectionByName, arg.Name, arg.UserID)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.Scope,
		&i.Provider,
		&i.Target,
		&i.Labels,
		&i.SecretEnvelope,
		&i.Enabled,
		&i.StatementTimeoutMs,
		&i.MaxRows,
		&i.MaxBytes,
		&i.LastCheckOutcome,
		&i.LastCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserIDByUsername = `-- name: FindUserIDByUsername :one
SELECT id FROM users WHERE username = $1
`

func (q *Queries) FindUserIDByUsername(ctx context.Context, username string) (string, error) {
	row := q.db.QueryRow(ctx, findUserIDByUsername, username)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertGrant = `-- name: InsertGrant :one
INSERT INTO grants (user_id, group_id, connection_id, created_by)
VALUES ($1::text::uuid, $2::text::uuid,
    $3::text::uuid, $4::text::uuid)
ON CONFLICT DO NOTHING
RETURNING user_id, group_id, connection_id, created_at, created_by
`

type InsertGrantParams struct {
	UserID       *string
	GroupID      *string
	ConnectionID string
	CreatedBy    string
}

type InsertGrantRow struct {
	UserID       *string
	GroupID      *string
	ConnectionID string
	CreatedAt    time.Time
	CreatedBy    string
}

// Exactly one recipient is non-NULL; the table's check enforces that and the
// two partial unique indexes make a repeated grant of either kind a no-op:
// no row is returned and the caller reads the existing one.
func (q *Queries) InsertGrant(ctx context.Context, arg InsertGrantParams) (InsertGrantRow, error) {
	row := q.db.QueryRow(ctx, insertGrant,
		arg.UserID,
		arg.GroupID,
		arg.ConnectionID,
		arg.CreatedBy,
	)
	var i InsertGrantRow
	err := row.Scan(
		&i.UserID,
		&i.GroupID,
		&i.ConnectionID,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listEffectiveAccess = `-- name: ListEffectiveAccess :many
SELECT c.id AS connection_id, c.name AS connection_name,
    gr.id AS group_id, gr.name AS group_name, g.created_at
FROM grants g
    JOIN connections c ON c.id = g.connection_id
    LEFT JOIN groups gr ON gr.id = g.group_id
WHERE (g.user_id = $1::text::uuid
        OR g.group_id IN (SELECT m.group_id FROM group_members m WHERE m.user_id = $1::text::uuid))
    AND ($2::text IS NULL OR c.id = $2::text::uuid)
ORDER BY c.name, (g.group_id IS NOT NULL), gr.name
LIMIT $3::integer
`

type ListEffectiveAccessParams struct {
	UserID       string
	ConnectionID *string
	LimitRows    int32
}

type ListEffectiveAccessRow struct {
	ConnectionID   string
	ConnectionName string
	GroupID        *string
	GroupName      *string
	CreatedAt      time.Time
}

// One row per configured path: a direct grant carries no group, a grant the
// subject inherits carries the group it came through. A connection reached
// twice is two entries, which is the provenance an administrator asked for.
func (q *Queries) ListEffectiveAccess(ctx context.Context, arg ListEffectiveAccessParams) ([]ListEffectiveAccessRow, error) {
	rows, err := q.db.Query(ctx, listEffectiveAccess, arg.UserID, arg.ConnectionID, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEffectiveAccessRow
	for rows.Next() {
		var i ListEffectiveAccessRow
		if err := rows.Scan(
			&i.ConnectionID,
			&i.ConnectionName,
			&i.GroupID,
			&i.GroupName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantedConnectionNames = `-- name: ListGrantedConnectionNames :many
SELECT c.name FROM connections c
WHERE EXISTS (
    SELECT 1 FROM grants g
    WHERE g.connection_id = c.id
        AND (g.user_id = $1::text::uuid
            OR g.group_id IN (SELECT m.group_id FROM group_members m WHERE m.user_id = $1::text::uuid))
)
ORDER BY c.name LIMIT $2::integer
`

type ListGrantedConnectionNamesParams struct {
	UserID    string
	LimitRows int32
}

func (q *Queries) ListGrantedConnectionNames(ctx context.Context, arg ListGrantedConnectionNamesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listGrantedConnectionNames, arg.UserID, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantedConnections = `-- name: ListGrantedConnections :many
SELECT c.id, c.name, c.title, c.description, c.scope, c.provider, c.target, c.labels, c.secret_envelope, c.enabled, c.statement_timeout_ms, c.max_rows, c.max_bytes, c.last_check_outcome, c.last_check_at, c.created_at, c.updated_at FROM connections c
WHERE EXISTS (
        SELECT 1 FROM grants g
        WHERE g.connection_id = c.id
            AND (g.user_id = $1::text::uuid
                OR g.group_id IN (SELECT m.group_id FROM group_members m WHERE m.user_id = $1::text::uuid))
    )
    AND c.labels @> COALESCE($2::jsonb, '{}'::jsonb)
    AND NOT EXISTS (
        SELECT 1 FROM jsonb_array_elements(COALESCE($3::jsonb, '[]'::jsonb)) AS excluded
        WHERE c.labels @> excluded
    )
    AND c.labels ?& COALESCE($4::text[], '{}'::text[])
ORDER BY c.name LIMIT $5::integer
`

type ListGrantedConnectionsParams struct {
	UserID    string
	Contains  []byte
	Excludes  []byte
	Keys      []string
	LimitRows int32
}

// The member listing: effectively accessible connections only, same selector
// semantics as the administrator listing, one row beyond the bound. EXISTS
// yields each connection once however many paths reach it, so neither this
// query nor its caller deduplicates.
func (q *Queries) ListGrantedConnections(ctx context.Context, arg ListGrantedConnectionsParams) ([]Connection, error) {
	rows, err := q.db.Query(ctx, listGrantedConnections,
		arg.UserID,
		arg.Contains,
		arg.Excludes,
		arg.Keys,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Connection
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.Description,
			&i.Scope,
			&i.Provider,
			&i.Target,
			&i.Labels,
			&i.SecretEnvelope,
			&i.Enabled,
			&i.StatementTimeoutMs,
			&i.MaxRows,
			&i.MaxBytes,
			&i.LastCheckOutcome,
			&i.LastCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrants = `-- name: ListGrants :many
SELECT g.user_id, u.username, g.group_id, gr.name AS group_name,
    g.connection_id, c.name AS connection_name,
    g.created_at, g.created_by, cb.username AS created_by_username
FROM grants g
    LEFT JOIN users u ON u.id = g.user_id
    LEFT JOIN groups gr ON gr.id = g.group_id
    JOIN connections c ON c.id = g.connection_id
    JOIN users cb ON cb.id = g.created_by
WHERE ($1::text IS NULL OR g.user_id = $1::text::uuid)
    AND ($2::text IS NULL OR g.group_id = $2::text::uuid)
    AND ($3::text IS NULL OR g.connection_id = $3::text::uuid)
ORDER BY (g.user_id IS NULL), COALESCE(u.username, gr.name), c.name
LIMIT $4::integer
`

type ListGrantsParams struct {
	UserID       *string
	GroupID      *string
	ConnectionID *string
	LimitRows    int32
}

type ListGrantsRow struct {
	UserID            *string
	Username          *string
	GroupID           *string
	GroupName         *string
	ConnectionID      string
	ConnectionName    string
	CreatedAt         time.Time
	CreatedBy         string
	CreatedByUsername string
}

// NULL filters match every row; the caller requests one row beyond its bound.
// User grants order before group grants, then by recipient name and connection.
func (q *Queries) ListGrants(ctx context.Context, arg ListGrantsParams) ([]ListGrantsRow, error) {
	rows, err := q.db.Query(ctx, listGrants,
		arg.UserID,
		arg.GroupID,
		arg.ConnectionID,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGrantsRow
	for rows.Next() {
		var i ListGrantsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.GroupID,
			&i.GroupName,
			&i.ConnectionID,
			&i.ConnectionName,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.CreatedByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
