// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package sqlc

import (
	"context"
	"time"
)

const checkGroupMembersColumns = `-- name: CheckGroupMembersColumns :exec
SELECT group_id, user_id, created_at, created_by FROM group_members LIMIT 0
`

func (q *Queries) CheckGroupMembersColumns(ctx context.Context) error {
	_, err := q.db.Exec(ctx, checkGroupMembersColumns)
	return err
}

const checkGroupsColumns = `-- name: CheckGroupsColumns :exec
SELECT id, name, description, created_at, updated_at FROM groups LIMIT 0
`

func (q *Queries) CheckGroupsColumns(ctx context.Context) error {
	_, err := q.db.Exec(ctx, checkGroupsColumns)
	return err
}

const countGroupGrants = `-- name: CountGroupGrants :one
SELECT count(*) FROM grants WHERE group_id = $1::text::uuid
`

func (q *Queries) CountGroupGrants(ctx context.Context, groupID string) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupGrants, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGroupMembers = `-- name: CountGroupMembers :one
SELECT count(*) FROM group_members WHERE group_id = $1::text::uuid
`

func (q *Queries) CountGroupMembers(ctx context.Context, groupID string) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupMembers, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteGroup = `-- name: DeleteGroup :execrows
DELETE FROM groups WHERE id = $1::text::uuid
`

func (q *Queries) DeleteGroup(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGroup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGroupMember = `-- name: DeleteGroupMember :execrows
DELETE FROM group_members
WHERE group_id = $1::text::uuid AND user_id = $2::text::uuid
`

type DeleteGroupMemberParams struct {
	GroupID string
	UserID  string
}

func (q *Queries) DeleteGroupMember(ctx context.Context, arg DeleteGroupMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGroupMember, arg.GroupID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findGroupByID = `-- name: FindGroupByID :one
SELECT id, name, description, created_at, updated_at FROM groups WHERE id = $1::text::uuid
`

func (q *Queries) FindGroupByID(ctx context.Context, id string) (Group, error) {
	row := q.db.QueryRow(ctx, findGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findGroupByName = `-- name: FindGroupByName :one
SELECT id, name, description, created_at, updated_at FROM groups WHERE name = $1
`

func (q *Queries) FindGroupByName(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRow(ctx, findGroupByName, name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findGroupMember = `-- name: FindGroupMember :one
SELECT m.group_id, g.name AS group_name, m.user_id, u.username,
    m.created_at, m.created_by, cb.username AS created_by_username
FROM group_members m
    JOIN groups g ON g.id = m.group_id
    JOIN users u ON u.id = m.user_id
    JOIN users cb ON cb.id = m.created_by
WHERE m.group_id = $1::text::uuid AND m.user_id = $2::text::uuid
`

type FindGroupMemberParams struct {
	GroupID string
	UserID  string
}

type FindGroupMemberRow struct {
	GroupID           string
	GroupName         string
	UserID            string
	Username          string
	CreatedAt         time.Time
	CreatedBy         string
	CreatedByUsername string
}

func (q *Queries) FindGroupMember(ctx context.Context, arg FindGroupMemberParams) (FindGroupMemberRow, error) {
	row := q.db.QueryRow(ctx, findGroupMember, arg.GroupID, arg.UserID)
	var i FindGroupMemberRow
	err := row.Scan(
		&i.GroupID,
		&i.GroupName,
		&i.UserID,
		&i.Username,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.CreatedByUsername,
	)
	return i, err
}

const groupNameExists = `-- name: GroupNameExists :one
SELECT EXISTS(SELECT 1 FROM groups WHERE name = $1)
`

func (q *Queries) GroupNameExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, groupNameExists, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertGroup = `-- name: InsertGroup :one
INSERT INTO groups (id, name, description)
VALUES ($1::text::uuid, $2, $3)
RETURNING id, name, description, created_at, updated_at
`

type InsertGroupParams struct {
	ID          string
	Name        string
	Description string
}

func (q *Queries) InsertGroup(ctx context.Context, arg InsertGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, insertGroup, arg.ID, arg.Name, arg.Description)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertGroupMember = `-- name: InsertGroupMember :one
INSERT INTO group_members (group_id, user_id, created_by)
VALUES ($1::text::uuid, $2::text::uuid, $3::text::uuid)
ON CONFLICT DO NOTHING
RETURNING group_id, user_id, created_at, created_by
`

type InsertGroupMemberParams struct {
	GroupID   string
	UserID    string
	CreatedBy string
}

// A repeated membership is a no-op: no row is returned and the caller reads
// the existing one.
func (q *Queries) InsertGroupMember(ctx context.Context, arg InsertGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, insertGroupMember, arg.GroupID, arg.UserID, arg.CreatedBy)
	var i GroupMember
	err := row.Scan(
		&i.GroupID,
		&i.UserID,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT u.id, u.username, u.role, u.disabled, u.created_at,
    m.created_at AS added_at, m.created_by AS added_by, ab.username AS added_by_username
FROM group_members m
    JOIN users u ON u.id = m.user_id
    JOIN users ab ON ab.id = m.created_by
WHERE m.group_id = $1::text::uuid
ORDER BY u.username LIMIT $2::integer
`

type ListGroupMembersParams struct {
	GroupID   string
	LimitRows int32
}

type ListGroupMembersRow struct {
	ID              string
	Username        string
	Role            string
	Disabled        bool
	CreatedAt       time.Time
	AddedAt         time.Time
	AddedBy         string
	AddedByUsername string
}

// The member listing is the safe user record plus how the membership came
// about, ordered by username, one row beyond the bound.
func (q *Queries) ListGroupMembers(ctx context.Context, arg ListGroupMembersParams) ([]ListGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, arg.GroupID, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupMembersRow
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.Disabled,
			&i.CreatedAt,
			&i.AddedAt,
			&i.AddedBy,
			&i.AddedByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupNames = `-- name: ListGroupNames :many
SELECT g.name FROM groups g JOIN group_members m ON m.group_id = g.id
WHERE m.user_id = $1::text::uuid
ORDER BY g.name LIMIT $2::integer
`

type ListGroupNamesParams struct {
	UserID    string
	LimitRows int32
}

// The identity question "which groups am I in", bounded like every listing.
func (q *Queries) ListGroupNames(ctx context.Context, arg ListGroupNamesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listGroupNames, arg.UserID, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT g.id, g.name, g.description, g.created_at, g.updated_at,
    (SELECT count(*) FROM group_members m WHERE m.group_id = g.id) AS members,
    (SELECT count(*) FROM grants r WHERE r.group_id = g.id) AS grants
FROM groups g ORDER BY g.name LIMIT $1::integer
`

type ListGroupsRow struct {
	ID          string
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Members     int64
	Grants      int64
}

// The counts an administrator needs before deleting a group come from the
// listing itself; the caller requests one row beyond its bound.
func (q *Queries) ListGroups(ctx context.Context, limitRows int32) ([]ListGroupsRow, error) {
	rows, err := q.db.Query(ctx, listGroups, limitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupsRow
	for rows.Next() {
		var i ListGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Members,
			&i.Grants,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockGroup = `-- name: LockGroup :one
SELECT id, name, description, created_at, updated_at FROM groups WHERE id = $1::text::uuid FOR UPDATE
`

func (q *Queries) LockGroup(ctx context.Context, id string) (Group, error) {
	row := q.db.QueryRow(ctx, lockGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups SET
    name = COALESCE($1::text, name),
    description = COALESCE($2::text, description),
    updated_at = CASE
        WHEN COALESCE($1::text, name) IS DISTINCT FROM name
            OR COALESCE($2::text, description) IS DISTINCT FROM description
        THEN clock_timestamp() ELSE updated_at END
WHERE id = $3::text::uuid
RETURNING id, name, description, created_at, updated_at
`

type UpdateGroupParams struct {
	Name        *string
	Description *string
	ID          string
}

// Absent fields keep their stored value; updated_at moves only when a supplied
// field differs, so a no-op update leaves the record untouched.
func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup, arg.Name, arg.Description, arg.ID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
