// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: initialize.sql

package sqlc

import (
	"context"
)

const bootstrapState = `-- name: BootstrapState :one
SELECT EXISTS(SELECT 1 FROM installation WHERE singleton AND initialized_at IS NOT NULL) AS initialized,
    EXISTS(SELECT 1 FROM users) AS has_users
`

type BootstrapStateRow struct {
	Initialized bool
	HasUsers    bool
}

func (q *Queries) BootstrapState(ctx context.Context) (BootstrapStateRow, error) {
	row := q.db.QueryRow(ctx, bootstrapState)
	var i BootstrapStateRow
	err := row.Scan(&i.Initialized, &i.HasUsers)
	return i, err
}

const checkLoginLimitsColumns = `-- name: CheckLoginLimitsColumns :exec
SELECT key, failures, expires_at FROM login_limits LIMIT 0
`

func (q *Queries) CheckLoginLimitsColumns(ctx context.Context) error {
	_, err := q.db.Exec(ctx, checkLoginLimitsColumns)
	return err
}

const checkSessionsColumns = `-- name: CheckSessionsColumns :exec
SELECT id, token_digest, user_id, kind, created_at, expires_at, revoked_at FROM sessions LIMIT 0
`

func (q *Queries) CheckSessionsColumns(ctx context.Context) error {
	_, err := q.db.Exec(ctx, checkSessionsColumns)
	return err
}

const checkUsersColumns = `-- name: CheckUsersColumns :exec
SELECT id, username, password_hash, role, disabled, created_at, updated_at FROM users LIMIT 0
`

func (q *Queries) CheckUsersColumns(ctx context.Context) error {
	_, err := q.db.Exec(ctx, checkUsersColumns)
	return err
}

const createInitialAdministrator = `-- name: CreateInitialAdministrator :exec
INSERT INTO users (id, username, password_hash, role)
VALUES ($1::text::uuid, $2, $3, 'admin')
`

type CreateInitialAdministratorParams struct {
	ID           string
	Username     string
	PasswordHash string
}

func (q *Queries) CreateInitialAdministrator(ctx context.Context, arg CreateInitialAdministratorParams) error {
	_, err := q.db.Exec(ctx, createInitialAdministrator, arg.ID, arg.Username, arg.PasswordHash)
	return err
}

const installationInitialized = `-- name: InstallationInitialized :one
SELECT EXISTS(SELECT 1 FROM installation WHERE singleton AND initialized_at IS NOT NULL)
`

func (q *Queries) InstallationInitialized(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, installationInitialized)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const lockTransaction = `-- name: LockTransaction :exec
SELECT pg_advisory_xact_lock($1::bigint)
`

func (q *Queries) LockTransaction(ctx context.Context, lockID int64) error {
	_, err := q.db.Exec(ctx, lockTransaction, lockID)
	return err
}

const markInstallationInitialized = `-- name: MarkInstallationInitialized :exec
INSERT INTO installation (singleton, initialized_at) VALUES (true, clock_timestamp())
`

func (q *Queries) MarkInstallationInitialized(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markInstallationInitialized)
	return err
}
