// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: limits.sql

package sqlc

import (
	"context"
	"time"
)

const cleanupLoginLimits = `-- name: CleanupLoginLimits :exec
DELETE FROM login_limits WHERE key IN (
    SELECT key FROM login_limits WHERE expires_at <= clock_timestamp()
    ORDER BY expires_at LIMIT 100
)
`

// Indexed, bounded cleanup; the caller holds the shared limit lock.
func (q *Queries) CleanupLoginLimits(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupLoginLimits)
	return err
}

const countLoginLimits = `-- name: CountLoginLimits :one
SELECT count(*) FROM login_limits
`

func (q *Queries) CountLoginLimits(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLoginLimits)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLoginLimit = `-- name: GetLoginLimit :one
SELECT failures, expires_at > clock_timestamp() AS active
FROM login_limits WHERE key = $1
`

type GetLoginLimitRow struct {
	Failures int32
	Active   bool
}

func (q *Queries) GetLoginLimit(ctx context.Context, key []byte) (GetLoginLimitRow, error) {
	row := q.db.QueryRow(ctx, getLoginLimit, key)
	var i GetLoginLimitRow
	err := row.Scan(&i.Failures, &i.Active)
	return i, err
}

const releaseLoginLimit = `-- name: ReleaseLoginLimit :exec
UPDATE login_limits SET failures = GREATEST(failures - 1, 0)
WHERE key = $1 AND expires_at = $2
`

type ReleaseLoginLimitParams struct {
	Key       []byte
	ExpiresAt time.Time
}

// Never decrement a newer window after an old reservation expires.
func (q *Queries) ReleaseLoginLimit(ctx context.Context, arg ReleaseLoginLimitParams) error {
	_, err := q.db.Exec(ctx, releaseLoginLimit, arg.Key, arg.ExpiresAt)
	return err
}

const reserveLoginLimit = `-- name: ReserveLoginLimit :one
INSERT INTO login_limits (key, failures, expires_at)
VALUES ($1, 1, clock_timestamp() + interval '5 minutes')
ON CONFLICT (key) DO UPDATE SET
    failures = CASE WHEN login_limits.expires_at <= clock_timestamp() THEN 1 ELSE login_limits.failures + 1 END,
    expires_at = CASE WHEN login_limits.expires_at <= clock_timestamp() THEN clock_timestamp() + interval '5 minutes' ELSE login_limits.expires_at END
RETURNING expires_at
`

func (q *Queries) ReserveLoginLimit(ctx context.Context, key []byte) (time.Time, error) {
	row := q.db.QueryRow(ctx, reserveLoginLimit, key)
	var expires_at time.Time
	err := row.Scan(&expires_at)
	return expires_at, err
}
