// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuthEvent struct {
	ID        pgtype.UUID
	ActorID   pgtype.UUID
	TargetID  pgtype.UUID
	SessionID pgtype.UUID
	Action    string
	Outcome   string
	CreatedAt time.Time
}

type Installation struct {
	Singleton     bool
	InitializedAt time.Time
}

type LoginLimit struct {
	Key       []byte
	Failures  int32
	ExpiresAt time.Time
}

type Session struct {
	ID          pgtype.UUID
	TokenDigest []byte
	UserID      pgtype.UUID
	Kind        string
	CreatedAt   time.Time
	ExpiresAt   time.Time
	RevokedAt   pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Username     string
	PasswordHash string
	Role         string
	Disabled     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
