// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"time"
)

const countEnabledAdministrators = `-- name: CountEnabledAdministrators :one
SELECT count(*) FROM users WHERE role = 'admin' AND NOT disabled
`

func (q *Queries) CountEnabledAdministrators(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEnabledAdministrators)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findUser = `-- name: FindUser :one
SELECT id::text, username, role, disabled, created_at
FROM users WHERE id = $1::text::uuid
`

type FindUserRow struct {
	ID        string
	Username  string
	Role      string
	Disabled  bool
	CreatedAt time.Time
}

func (q *Queries) FindUser(ctx context.Context, id string) (FindUserRow, error) {
	row := q.db.QueryRow(ctx, findUser, id)
	var i FindUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.Disabled,
		&i.CreatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (id, username, password_hash, role)
VALUES ($1::text::uuid, $2, $3, 'member')
RETURNING id::text, username, role, disabled, created_at
`

type InsertUserParams struct {
	ID           string
	Username     string
	PasswordHash string
}

type InsertUserRow struct {
	ID        string
	Username  string
	Role      string
	Disabled  bool
	CreatedAt time.Time
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.ID, arg.Username, arg.PasswordHash)
	var i InsertUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.Disabled,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id::text, username, role, disabled, created_at
FROM users ORDER BY username LIMIT $1::integer
`

type ListUsersRow struct {
	ID        string
	Username  string
	Role      string
	Disabled  bool
	CreatedAt time.Time
}

// The caller requests one row beyond its bound to detect truncation.
func (q *Queries) ListUsers(ctx context.Context, limitRows int32) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, limitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.Disabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserDisabled = `-- name: SetUserDisabled :one
UPDATE users SET disabled = $1, updated_at = clock_timestamp()
WHERE id = $2::text::uuid
RETURNING id::text, username, role, disabled, created_at
`

type SetUserDisabledParams struct {
	Disabled bool
	ID       string
}

type SetUserDisabledRow struct {
	ID        string
	Username  string
	Role      string
	Disabled  bool
	CreatedAt time.Time
}

func (q *Queries) SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) (SetUserDisabledRow, error) {
	row := q.db.QueryRow(ctx, setUserDisabled, arg.Disabled, arg.ID)
	var i SetUserDisabledRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.Disabled,
		&i.CreatedAt,
	)
	return i, err
}

const setUserPasswordHash = `-- name: SetUserPasswordHash :exec
UPDATE users SET password_hash = $1, updated_at = clock_timestamp()
WHERE id = $2::text::uuid
`

type SetUserPasswordHashParams struct {
	PasswordHash string
	ID           string
}

func (q *Queries) SetUserPasswordHash(ctx context.Context, arg SetUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, setUserPasswordHash, arg.PasswordHash, arg.ID)
	return err
}

const setUserRole = `-- name: SetUserRole :one
UPDATE users SET role = $1, updated_at = clock_timestamp()
WHERE id = $2::text::uuid
RETURNING id::text, username, role, disabled, created_at
`

type SetUserRoleParams struct {
	Role string
	ID   string
}

type SetUserRoleRow struct {
	ID        string
	Username  string
	Role      string
	Disabled  bool
	CreatedAt time.Time
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) (SetUserRoleRow, error) {
	row := q.db.QueryRow(ctx, setUserRole, arg.Role, arg.ID)
	var i SetUserRoleRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.Disabled,
		&i.CreatedAt,
	)
	return i, err
}

const usernameExists = `-- name: UsernameExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE username = $1)
`

func (q *Queries) UsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, usernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
